### ISSUE TITLE
Gem shakes on touch when running on plus size device in simulator

### ISSUE THREAD

**Issue by stevenroach7** [stevenroach7/Ceres#14]
When the game is played with a plus size iPhone Simulator (6 plus, 6s plus, and 7 plus), touched gems rapidly shake.

**Comment by stevenroach7** [comment]
Testing for gem touch bug on different devices
4/14, Last commit 40decc89f1db9e2565b1127efe52de555f2de118

SE - Good
7 Plus - Real Bad, Might just be too much going on. Particle effects seem laggy
7 - Good
6s Plus - Messed up 
6s - Good
6 Plus - Messed up
6 - Good
5s - Good
5 - Good
iPad pro 12.9 - Good
iPad pro 9.7 - Good
iPad air 2 - Good
iPad air - Good

I also tried simulating a plus size device on a past version of the game before multi-touch was added and the same bug occurred.

**Comment by pcantrell** [comment]
> 7 Plus - Real Bad, Might just be too much going on. Particle effects seem laggy

You can’t rely on the simulator to give you useful information about performance — either “too slow” or “too fast.“ When you do a simulator build, it compiles your app for x86 instead of ARM and runs natively on your dev machine, so it generally runs much faster than the real device — but it simulates the device GPU, which generally makes graphics stuff much slower. Except when it’s all just the opposite. Once you’ve fixed the touch coordinate bug, you'll have to find a real 6+ / 7+ to get useful performance info.

**Comment by stevenroach7** [comment]
I tested on an iPhone 6+ and encountered no problems. I think this is probably a simulator bug so I'm going to close this issue. If we have the opportunity to test on an iPhone 6s+ and 7+, we should.
